# Generated by Django 5.2 on 2025-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainservice',
            name='benefits_intro',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='benefits_list',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='benefits_outro',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='benefits_title',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_answer_1',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_answer_2',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_answer_3',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_answer_4',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_answer_5',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_question_1',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_question_2',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_question_3',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_question_4',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_question_5',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_subtitle',
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='faq_title',
        ),
        migrations.AddField(
            model_name='mainservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='main_services/icons/'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='benefits_intro',
            field=models.TextField(blank=True, verbose_name='Đoạn giới thiệu lợi ích'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='benefits_list',
            field=models.TextField(blank=True, verbose_name='Danh sách lợi ích (mỗi dòng 1 lợi ích)'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='benefits_outro',
            field=models.TextField(blank=True, verbose_name='Đoạn kết lợi ích'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='benefits_title',
            field=models.CharField(default='Các Lợi Ích Chính', max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_answer_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_answer_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_answer_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_answer_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_answer_5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_question_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_question_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_question_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_question_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_question_5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subservice',
            name='faq_title',
            field=models.CharField(default='Mọi điều bạn cần biết', max_length=255),
        ),
    ]
