# Generated by Django 5.2 on 2025-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_mainservice_benefits_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainservice',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='main_services/icons/'),
        ),
    ]
