# Generated by Django 5.2 on 2025-05-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_subservice_benefits_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='detail_content',
            field=models.TextField(blank=True, verbose_name='Nội dung chi tiết'),
        ),
    ]
