# Generated by Django 5.2 on 2025-05-10 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_subservice_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='main_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.mainservice'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.subservice'),
        ),
    ]
