# Generated by Django 5.2 on 2025-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceimage_main_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainservice',
            old_name='image',
            new_name='benefits_image',
        ),
        migrations.RemoveField(
            model_name='serviceimage',
            name='main_service',
        ),
        migrations.AddField(
            model_name='mainservice',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_service_images/'),
        ),
    ]
