# Generated by Django 5.2 on 2025-05-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_mainservice_intro_detail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
