# Generated by Django 5.2 on 2025-05-19 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_bio_expertise_doctor_bio_expertise_1_and_more'),
        ('services', '0010_alter_subservice_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ tên khách hàng')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('date', models.DateField(verbose_name='Ngày hẹn')),
                ('time', models.TimeField(verbose_name='Giờ hẹn')),
                ('reason', models.CharField(choices=[('general', 'Khám tổng quát'), ('first', 'Khám lần đầu'), ('specific', 'Vấn đề cụ thể')], max_length=100, verbose_name='Lý do khám')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor', verbose_name='Bác sĩ')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.subservice', verbose_name='Dịch vụ')),
            ],
        ),
    ]
