# Generated by Django 5.2 on 2025-05-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_doctor_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='diagnosis',
            field=models.IntegerField(default=90, verbose_name='Kiểm tra và chẩn đoán'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='healing_therapy',
            field=models.IntegerField(default=85, verbose_name='Liệu pháp chữa lành'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pain_management',
            field=models.IntegerField(default=80, verbose_name='Quản lý đau'),
        ),
    ]
