# Generated by Django 5.2 on 2025-05-05 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_diagnosis_doctor_healing_therapy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bio_expertise',
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_expertise_1',
            field=models.TextField(blank=True, null=True, verbose_name='Chuyên môn - Đoạn 1'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_expertise_2',
            field=models.TextField(blank=True, null=True, verbose_name='Chuyên môn - Đoạn 2'),
        ),
    ]
